/* An illustrative peer network: multiple employers and people, no central broker. */
const communityMembers=[
 {id:'landscape',kind:'person',x:13,y:15,label:'Landschaftsgärtner',image:'hero-gaertner.jpg',crop:'74% 30%',zoom:'270%',title:'Gute Arbeit beginnt mit einem gemeinsamen Interesse.',text:'Gärten gestalten. Draußen arbeiten. Ein Team finden, das dazu passt.'},
 {id:'gardens',kind:'business',x:52,y:15,label:'GaLaBau-Betrieb',sub:'Gärten gestalten',image:'titel-galabau-gartenanlage.webp',title:'Ein Betrieb. Viele mögliche Begegnungen.',text:'Menschen lernen Projekte, Aufgaben und das Team dahinter kennen.'},
 {id:'gardener',kind:'person',x:87,y:31,label:'Gärtnerin',image:'team-miteinander-v2.jpg',crop:'63% -5%',zoom:'500%',title:'Pflanzenwissen trifft neue Perspektiven.',text:'Baumschule, Gartenbau oder Gartencenter: Können verbindet über Betriebsgrenzen hinweg.'},
 {id:'foreman',kind:'person',x:36,y:42,label:'Vorarbeiter',image:'team-miteinander-v2.jpg',crop:'39% 26%',zoom:'500%',title:'Erfahrung, die andere weiterbringt.',text:'Menschen mit Erfahrung und Betriebe mit neuen Aufgaben entdecken einander.'},
 {id:'nursery',kind:'business',x:14,y:69,label:'Baumschule',sub:'Wachstum begleiten',image:'kat-kultivierung.jpg',title:'Aus Pflanzenbegeisterung wird eine Verbindung.',text:'Einblick bekommen. Gemeinsamkeiten entdecken. Miteinander ins Gespräch kommen.'},
 {id:'arborist',kind:'person',x:63,y:58,label:'Baumpfleger',image:'team-miteinander-v2.jpg',crop:'88% 29%',zoom:'500%',title:'Das richtige Umfeld für das eigene Können.',text:'Neue Aufgaben und vertraute Werte: Hier entstehen Möglichkeiten für beide Seiten.'},
 {id:'retail',kind:'business',x:85,y:82,label:'Gartencenter',sub:'Begeisterung teilen',image:'kat-handel.jpg',title:'Menschen mit derselben Begeisterung.',text:'Pflanzen, Beratung und Miteinander: Ein erster Eindruck kann viel in Bewegung bringen.'},
 {id:'advisor',kind:'person',x:43,y:89,label:'Fachberaterin',image:'team-miteinander-v2.jpg',crop:'12% 24%',zoom:'500%',title:'Ein neues Team beginnt mit dem Kennenlernen.',text:'Persönlichkeit und Pflanzenwissen treffen auf Betriebe mit passenden Perspektiven.'}
];
const communityLinks=[[0,1],[0,3],[0,4],[1,2],[1,3],[1,5],[2,4],[2,6],[2,7],[3,4],[3,5],[3,6],[4,7],[4,5],[5,6],[5,7],[6,7]];
function communitySvg(){return `<svg class="community-lines" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="connection-gradient"><stop stop-color="#c6f17b"/><stop offset="1" stop-color="#e1f7bd"/></linearGradient></defs>${communityLinks.map(([a,b],i)=>{const p=communityMembers[a],q=communityMembers[b],x=p.x*10,y=p.y*7,x2=q.x*10,y2=q.y*7,bend=(i%2?1:-1)*35;const path=`M ${x} ${y} Q ${(x+x2)/2+bend} ${(y+y2)/2-bend} ${x2} ${y2}`;return `<g data-connection="${a}-${b}"><path class="community-thread" d="${path}"/><path class="community-current" pathLength="100" d="${path}" style="--flow-delay:-${i*.63}s;--flow-direction:${i%2?'reverse':'normal'}"/></g>`}).join('')}${[[4,40],[30,9],[71,12],[95,55],[39,69],[9,91],[67,84],[79,44],[22,91],[58,35]].map(([x,y],i)=>`<circle class="community-spark" cx="${x*10}" cy="${y*7}" r="${i%3?3:5}" style="--flow-delay:-${i*.4}s"/>`).join('')}</svg>`}
function communityNode(m,i){return `<button class="community-member ${m.kind}" data-member="${i}" style="--x:${m.x}%;--y:${m.y}%;--bob-delay:-${i*.8}s" aria-pressed="${i===1}" aria-label="${m.label}: Verbindungen entdecken">${m.kind==='person'?`<span class="member-portrait" role="img" aria-label="Beispielhafte Person" style="background-image:url('assets/${m.image}');background-position:${m.crop};background-size:${m.zoom}"></span><span class="member-label">${m.label}</span>`:`<span class="business-image"><img src="assets/${m.image}" alt="" loading="lazy">${fi('leaf')}</span><span class="business-identity"><small>${m.sub}</small><strong>${m.label}</strong></span>`}<span class="member-ring" aria-hidden="true"></span></button>`}
function communityNetwork(){return `<section class="real-network community-section" id="so-gehts" aria-labelledby="community-title"><div class="container community-layout"><div class="community-copy"><div class="eyebrow">HIER WÄCHST MITEINANDER.</div><h2 id="community-title">Viele Menschen.<br>Viele Betriebe.<br><em>Ein Miteinander.</em></h2><p>Entdecken. Kennenlernen. Zusammenfinden.<br>Mit Menschen, die Ihre Begeisterung fürs Grüne teilen.</p><div class="community-legend"><span><i class="legend-person"></i>Menschen</span><span><i class="legend-business"></i>Betriebe</span></div><p class="community-invitation">${fi('up')} Tippen Sie auf ein Profil und entdecken Sie seine Verbindungen.</p><button class="btn" id="network-start">Ins Gespräch kommen ${fi('arrow')}</button></div><div class="community-experience"><div class="community-map" aria-label="Beispielnetzwerk erkunden">${communitySvg()}${communityMembers.map(communityNode).join('')}<span class="community-whisper" aria-hidden="true"><span>↗</span> Neue Perspektiven.</span></div><div class="community-detail" id="community-detail" aria-live="off"><div class="community-detail-top"><span class="connection-avatar-stack" id="connection-avatars"></span><span id="connection-context">GaLaBau-Betrieb · Verbindungen entdecken</span><span class="connection-mark">${fi('people')}</span></div><h3 id="connection-title">Ein Betrieb. Viele mögliche Begegnungen.</h3><p id="connection-text">Menschen lernen Projekte, Aufgaben und das Team dahinter kennen.</p></div><div class="community-bottom"><span>Illustrative Profile · Netzwerk zum Entdecken</span><button class="motion-toggle" data-motion aria-pressed="false">Ⅱ Animationen pausieren</button></div></div></div></section>`}
let communityCleanup=null;
function bindCommunity(){
 if(communityCleanup){communityCleanup();communityCleanup=null}
 const map=document.querySelector('.community-map');if(!map)return;
 let selected=1,visible=false,interacting=false,lastInteraction=0;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function selectMember(index,manual=false){
  selected=index;const member=communityMembers[index],neighbors=new Set([index]);
  communityLinks.forEach(([a,b])=>{if(a===index)neighbors.add(b);if(b===index)neighbors.add(a)});
  map.querySelectorAll('[data-member]').forEach(b=>{const n=Number(b.dataset.member);b.setAttribute('aria-pressed',String(n===index));b.classList.toggle('connected',neighbors.has(n));b.classList.toggle('quiet',!neighbors.has(n))});
  map.querySelectorAll('[data-connection]').forEach(g=>g.classList.toggle('connected',g.dataset.connection.split('-').map(Number).includes(index)));
  document.querySelector('#community-detail').setAttribute('aria-live',manual?'polite':'off');
  document.querySelector('#connection-context').textContent=member.label+' · '+(neighbors.size-1)+' Verbindungen';
  document.querySelector('#connection-title').textContent=member.title;
  document.querySelector('#connection-text').textContent=member.text;
  document.querySelector('#connection-avatars').innerHTML=[...neighbors].slice(0,4).map(n=>{const m=communityMembers[n];return m.kind==='person'?`<span style="background-image:url('assets/${m.image}');background-position:${m.crop};background-size:${m.zoom}"></span>`:`<span class="connection-business">${fi('leaf')}</span>`}).join('');
 }
 map.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>{lastInteraction=Date.now();selectMember(Number(b.dataset.member),true)});
 const enter=()=>interacting=true,leave=()=>interacting=false;
 map.addEventListener('pointerenter',enter);map.addEventListener('pointerleave',leave);
 const focus=()=>{lastInteraction=Date.now()};map.addEventListener('focusin',focus);
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;map.classList.toggle('community-asleep',!visible)},{threshold:.15});observer.observe(map);
 const sequence=[1,2,4,7,6,3,0,5];let step=0;
 const timer=setInterval(()=>{if(!visible||interacting||document.hidden||motionPaused||reduced.matches||Date.now()-lastInteraction<14000)return;step=(step+1)%sequence.length;selectMember(sequence[step])},4300);
 selectMember(selected);
 communityCleanup=()=>{clearInterval(timer);observer.disconnect();map.removeEventListener('pointerenter',enter);map.removeEventListener('pointerleave',leave);map.removeEventListener('focusin',focus)};
}
function employerFilm(){return `<div class="employer-film" id="film"><div class="film-player"><video id="gc-employer-film" controls playsinline preload="none" poster="https://www.green-careers.de/images/erklaervideo-thumbnail.png" aria-label="Green Careers – das Karrierenetzwerk für Arbeitgeber"><source src="https://www.green-careers.de/videos/erklaervideo.mp4" type="video/mp4">Ihr Browser kann das Video nicht abspielen. <a href="https://www.green-careers.de/videos/erklaervideo.mp4">Video öffnen</a></video><button class="film-play" id="film-play" aria-label="Green-Careers-Video abspielen"><span>▶</span><strong>Green Careers kennenlernen</strong></button></div><div class="film-copy"><span class="eyebrow">GREEN CAREERS IM FILM</span><h3>Ihre Menschen.<br><em>Ihre Möglichkeiten.</em></h3><p>So bringen wir Betriebe und Fachkräfte der grünen Branche zusammen.</p><button class="film-text-play" id="film-text-play">Film ansehen · 2 Min. ${fi('arrow')}</button><span class="film-signature">MITTEN IN IHRER BRANCHE.</span></div></div>`}
function bindEmployerFilm(){const v=document.querySelector('#gc-employer-film');if(!v)return;const play=()=>{v.play().catch(()=>{document.querySelector('#film-play').hidden=false})};document.querySelector('#film-play').onclick=play;document.querySelector('#film-text-play').onclick=()=>{v.scrollIntoView({behavior:'smooth',block:'center'});play()};v.addEventListener('play',()=>document.querySelector('#film-play').hidden=true);v.addEventListener('ended',()=>document.querySelector('#film-play').hidden=false)}
