/* Illustrative occupations and employers, connected through Green Careers. */
const communityMembers=[
 {id:'landscape',kind:'person',x:16,y:11,label:'Landschaftsgärtner',image:'network-landscape-v20.jpg',crop:'50% 35%',zoom:'145%',title:'Landschaftsgärtner für Ihren GaLaBau-Betrieb.',text:'Pflanzarbeiten, Wegebau oder Gartenanlagen: Green Careers macht Ihre Stelle für Menschen aus dem Garten- und Landschaftsbau sichtbar.'},
 {id:'gardens',kind:'business',x:66,y:11,label:'GaLaBau-Betrieb',sub:'Bauen und pflegen',image:'titel-galabau-gartenanlage.webp',title:'Mitarbeiter für Baustelle und Grünpflege.',text:'Landschaftsgärtner, Vorarbeiter und Gärtner in der Grünpflege: Zeigen Sie auf Green Careers, wen Ihr Betrieb sucht und welche Aufgaben anstehen.'},
 {id:'gardener',kind:'person',x:85,y:33,label:'Gärtnerin in der Grünpflege',image:'team-miteinander-v2.jpg',crop:'63% -5%',zoom:'500%',title:'Verstärkung für Ihre Grünpflege.',text:'Rasen mähen, Hecken schneiden, Pflanzflächen pflegen: Diese Aufgaben fallen vor allem in GaLaBau-Betrieben und auch in Baumschulen an.'},
 {id:'foreman',kind:'person',x:14,y:37,label:'Vorarbeiter',image:'team-miteinander-v2.jpg',crop:'39% 26%',zoom:'500%',title:'Vorarbeiter für Ihre Kolonnen.',text:'Sie suchen jemanden, der auf der Baustelle den Überblick behält und das Team anleitet? Beschreiben Sie die Verantwortung in Ihrer Stellenanzeige.'},
 {id:'nursery',kind:'business',x:18,y:86,label:'Baumschule',sub:'Pflege und Verkauf',image:'kat-kultivierung.jpg',title:'Gärtner für Pflege und Pflanzenverkauf.',text:'Für die Beratung Ihrer Kunden brauchen Sie Pflanzenkenntnis, für die Grünpflege praktische Erfahrung. Green Careers verbindet Ihre Baumschule mit diesen Berufsgruppen.'},
 {id:'arborist',kind:'person',x:85,y:60,label:'Baumpfleger',image:'team-miteinander-v2.jpg',crop:'88% 29%',zoom:'500%',title:'Baumpfleger für Ihren Baumpflegebetrieb.',text:'Ob Seilklettertechnik oder Hubarbeitsbühne: Machen Sie deutlich, welche Erfahrung und Qualifikationen Sie für Ihre Aufträge benötigen.'},
 {id:'retail',kind:'business',x:83,y:87,label:'Gartencenter',sub:'Pflanzenberatung',image:'kat-handel.jpg',title:'Verkaufsgärtner für Ihr Gartencenter.',text:'Pflanzen erklären, Kunden beraten und die Verkaufsfläche betreuen: Zeigen Sie Verkaufsgärtnern, was sie in Ihrem Gartencenter erwartet.'},
 {id:'advisor',kind:'person',x:52,y:85,label:'Verkaufsgärtner',image:'network-sales-gardener-v20.jpg',crop:'50% 32%',zoom:'145%',title:'Pflanzenkenntnis für Ihre Kundenberatung.',text:'Verkaufsgärtner werden in Baumschulen und Gartencentern gebraucht. Über Green Careers entdecken sie Stellen, bei denen ihr Pflanzenwissen gefragt ist.'},
 {id:'treecare',kind:'business',x:20,y:61,label:'Baumpflegebetrieb',sub:'Arbeiten am Baum',image:'titel-baumpflege-klettertechnik.webp',title:'Baumpfleger für Ihre Aufträge.',text:'Baumkontrolle, Kronenpflege oder Fällung: Stellen Sie Ihren Betrieb und die konkreten Aufgaben vor, für die Sie Baumpfleger suchen.'},
 {id:'greencareers',kind:'hub',x:50,y:44,label:'Green Careers',image:'logo-dark-sm.png',title:'Green Careers bringt beide Seiten zusammen.',text:'Sie veröffentlichen Ihre Stelle und stellen Ihren Betrieb vor. Interessenten finden passende Angebote und können sich bei Ihnen bewerben.'}
];
// Occupation-to-employer relationships. Every displayed route passes through Green Careers.
const communityMatches=[[0,1],[2,1],[2,4],[3,1],[5,8],[7,4],[7,6]];
const communityHub=communityMembers.length-1;
const communityLinks=communityMembers.slice(0,-1).map((_,i)=>[i,communityHub]);
function communitySvg(){
 const hub=communityMembers[communityHub];
 return `<svg class="community-lines" viewBox="0 0 1000 800" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="connection-gradient"><stop stop-color="#c6f17b"/><stop offset="1" stop-color="#e1f7bd"/></linearGradient></defs>${communityLinks.map(([a],i)=>{const p=communityMembers[a],x=p.x*10,y=p.y*8,x2=hub.x*10,y2=hub.y*8,bend=(i%2?1:-1)*24;const path=`M ${x} ${y} Q ${(x+x2)/2+bend} ${(y+y2)/2-bend} ${x2} ${y2}`;return `<g data-connection="${a}"><path class="community-thread" d="${path}"/><path class="community-current" pathLength="100" d="${path}" style="--flow-delay:-${i*.63}s;--flow-direction:${p.kind==='business'?'reverse':'normal'}"/></g>`}).join('')}${[[5,46],[36,8],[96,49],[37,69],[9,95],[68,69],[67,39]].map(([x,y],i)=>`<circle class="community-spark" cx="${x*10}" cy="${y*8}" r="${i%3?3:5}" style="--flow-delay:-${i*.4}s"/>`).join('')}</svg>`;
}
function communityNode(m,i){
 const inner=m.kind==='person'?`<span class="member-portrait" role="img" aria-label="Beispielporträt: ${m.label}" style="background-image:url('assets/${m.image}');background-position:${m.crop};background-size:${m.zoom}"></span><span class="member-label">${m.label}</span>`:m.kind==='hub'?`<span class="hub-logo"><img src="assets/logo-dark-sm.png" alt="Green Careers" width="99" height="58"></span><span class="hub-caption">Bringt Sie zusammen.</span>`:`<span class="business-image"><img src="assets/${m.image}" alt="" loading="lazy">${fi('leaf')}</span><span class="business-identity"><small>${m.sub}</small><strong>${m.label.replace('Baumpflegebetrieb','Baumpflege<wbr>betrieb')}</strong></span>`;
 return `<button class="community-member ${m.kind}" data-member="${i}" style="--x:${m.x}%;--y:${m.y}%;--bob-delay:-${i*.8}s" aria-pressed="${i===communityHub}" aria-label="${m.label}: Verbindungen entdecken">${inner}<span class="member-ring" aria-hidden="true"></span></button>`;
}
function communityNetwork(){return `<section class="real-network community-section" id="so-gehts" aria-labelledby="community-title"><div class="container community-layout"><div class="community-copy"><div class="eyebrow">GREEN CAREERS VERBINDET</div><h2 id="community-title">Fachkräfte.<br>Betriebe.<br><em>Ein Netzwerk.</em></h2><p>Der Landschaftsgärtner für Ihre Baustellen. Die Gärtnerin für Ihre Grünpflege. Der Verkaufsgärtner für Ihre Pflanzenabteilung.</p><p class="community-promise">Green Careers bringt Sie miteinander in Kontakt.</p><div class="community-legend"><span><i class="legend-person"></i>Berufe</span><span><i class="legend-business"></i>Betriebe</span></div><p class="community-invitation">${fi('up')} Beruf oder Betrieb antippen: passende Verbindungen ansehen.</p><button class="btn" id="network-start" data-price-entry="once">Pakete und Preise ${fi('arrow')}</button></div><div class="community-experience"><div class="community-map" aria-label="Green Careers verbindet Berufe und Betriebe">${communitySvg()}${communityMembers.map(communityNode).join('')}</div><div class="community-detail" id="community-detail" aria-live="off"><div class="community-detail-top"><span class="connection-avatar-stack" id="connection-avatars"></span><span id="connection-context">Green Careers · Das Karrierenetzwerk</span><span class="connection-mark">${fi('people')}</span></div><h3 id="connection-title">Green Careers bringt beide Seiten zusammen.</h3><p id="connection-text">Sie veröffentlichen Ihre Stelle und stellen Ihren Betrieb vor. Interessenten finden passende Angebote und können sich bei Ihnen bewerben.</p></div><div class="community-bottom"><span>Beispielhafte Berufe und Betriebe · Generierte Porträts</span><button class="motion-toggle" data-motion aria-pressed="false">Ⅱ Animationen pausieren</button></div></div></div></section>`}
let communityCleanup=null;
function bindCommunity(){
 if(communityCleanup){communityCleanup();communityCleanup=null}
 const map=document.querySelector('.community-map');if(!map)return;
 let selected=communityHub,visible=false,interacting=false,lastInteraction=0;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function selectMember(index,manual=false){
  selected=index;const member=communityMembers[index],neighbors=new Set([index,communityHub]);
  if(index===communityHub)communityMembers.forEach((_,i)=>neighbors.add(i));
  else communityMatches.forEach(([a,b])=>{if(a===index)neighbors.add(b);if(b===index)neighbors.add(a)});
  map.querySelectorAll('[data-member]').forEach(b=>{const n=Number(b.dataset.member);b.setAttribute('aria-pressed',String(n===index));b.classList.toggle('connected',neighbors.has(n));b.classList.toggle('quiet',!neighbors.has(n))});
  map.querySelectorAll('[data-connection]').forEach(g=>g.classList.toggle('connected',neighbors.has(Number(g.dataset.connection))));
  document.querySelector('#community-detail').setAttribute('aria-live',manual?'polite':'off');
  const count=neighbors.size-2;
  document.querySelector('#connection-context').textContent=index===communityHub?'Green Careers · Das Karrierenetzwerk':member.label+' · '+count+' '+(member.kind==='person'?(count===1?'Betriebsart':'Betriebsarten'):(count===1?'Beruf':'Berufe'));
  document.querySelector('#connection-title').textContent=member.title;
  document.querySelector('#connection-text').textContent=member.text;
  document.querySelector('#connection-avatars').innerHTML=[...neighbors].filter(n=>n!==communityHub).slice(0,4).map(n=>{const m=communityMembers[n];return m.kind==='person'?`<span style="background-image:url('assets/${m.image}');background-position:${m.crop};background-size:${m.zoom}"></span>`:`<span class="connection-business">${fi('leaf')}</span>`}).join('');
 }
 map.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>{lastInteraction=Date.now();selectMember(Number(b.dataset.member),true)});
 const enter=()=>interacting=true,leave=()=>interacting=false;
 map.addEventListener('pointerenter',enter);map.addEventListener('pointerleave',leave);
 const focus=()=>{lastInteraction=Date.now()};map.addEventListener('focusin',focus);
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;map.classList.toggle('community-asleep',!visible)},{threshold:.15});observer.observe(map);
 const sequence=[communityHub,1,0,2,4,7,6,8,5,3];let step=0;
 const timer=setInterval(()=>{if(!visible||interacting||document.hidden||motionPaused||reduced.matches||Date.now()-lastInteraction<14000||map.contains(document.activeElement))return;step=(step+1)%sequence.length;selectMember(sequence[step])},6500);
 selectMember(selected);
 communityCleanup=()=>{clearInterval(timer);observer.disconnect();map.removeEventListener('pointerenter',enter);map.removeEventListener('pointerleave',leave);map.removeEventListener('focusin',focus)};
}
function employerFilm(){return `<div class="employer-film" id="film"><div class="film-player"><video id="gc-employer-film" controls playsinline preload="none" poster="https://www.green-careers.de/images/erklaervideo-thumbnail.png" aria-label="Green Careers – das Karrierenetzwerk für Arbeitgeber"><source src="https://www.green-careers.de/videos/erklaervideo.mp4" type="video/mp4">Ihr Browser kann das Video nicht abspielen. <a href="https://www.green-careers.de/videos/erklaervideo.mp4">Video öffnen</a></video><button class="film-play" id="film-play" aria-label="Green-Careers-Video abspielen"><span>▶</span><strong>Green Careers kennenlernen</strong></button></div><div class="film-copy"><span class="eyebrow">GREEN CAREERS IM FILM</span><h3>So funktioniert<br><em>Green Careers.</em></h3><p>Sehen Sie, wie Green Careers Betriebe und Bewerber aus der grünen Branche zusammenbringt.</p><button class="film-text-play" id="film-text-play">Film ansehen · 2 Min. ${fi('arrow')}</button><span class="film-signature">MITARBEITERSUCHE FÜR GRÜNE BETRIEBE</span></div></div>`}
function bindEmployerFilm(){const v=document.querySelector('#gc-employer-film');if(!v)return;const play=()=>{v.play().catch(()=>{document.querySelector('#film-play').hidden=false})};document.querySelector('#film-play').onclick=play;document.querySelector('#film-text-play').onclick=()=>{v.scrollIntoView({behavior:'smooth',block:'center'});play()};v.addEventListener('play',()=>document.querySelector('#film-play').hidden=true);v.addEventListener('ended',()=>document.querySelector('#film-play').hidden=false)}
