/* Curated, published posts. Local original artwork keeps the preview fast. */
const gcInstagramProfile='https://www.instagram.com/greencareers.de/';
const gcFeaturedPosts=[
 {image:'2026-09-w2-fr-brand.jpg',url:'https://www.instagram.com/p/DdJylIqDiDU/',date:'2026-09-11',displayDate:'11.09.2026',topic:'Das Netzwerk',title:'Wer steckt hinter Green Careers?',alt:'Green Careers: Das Karrierenetzwerk. Für die grüne Branche. Team beim gemeinsamen Arbeiten.',slides:1},
 {image:'2026-09-w1-mi-bewerber-diskret.jpg',url:'https://www.instagram.com/p/Dcx-UDjlUu9/',date:'2026-09-02',displayDate:'02.09.2026',topic:'Dein nächster Schritt',title:'Umschauen. Mit einem guten Gefühl.',alt:'Green Careers: Umschauen erlaubt. 100 % diskret. Helles Motiv mit einem grünen Zweig.',slides:1},
 {image:'2026-09-w2-mi-bewerber-k-s1.jpg',url:'https://www.instagram.com/p/DdD_1rDlldD/',date:'2026-09-09',displayDate:'09.09.2026',topic:'So funktioniert’s',title:'Ein Jobwechsel in drei Schritten.',alt:'Green Careers: So läuft’s. Ohne Bewerbungsstress. Zwei Menschen beim Kennenlernen.',slides:4},
 {image:'2026-09-v4-chef-frage.jpg',url:'https://www.instagram.com/p/Dc8Ki4Glmy-/',date:'2026-09-06',displayDate:'06.09.2026',topic:'Frage an die Kolonne',title:'Woran erkennst du einen guten Chef?',alt:'Green Careers: Woran erkennst du einen guten Chef? Ehrliche Antworten. Kolonne im Garten- und Landschaftsbau.',slides:1}
];
function instagramIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>'}
function instagramSection(){return `<section class="instagram-section" id="instagram" aria-labelledby="instagram-title"><div class="container"><div class="instagram-heading"><div><div class="eyebrow">${instagramIcon()} EINBLICKE IN GRÜNE BERUFE</div><h2 id="instagram-title">Green Careers<br><em>auf Instagram.</em></h2><p>Was macht einen guten Arbeitgeber aus? Wie läuft ein Jobwechsel ab?<br class="instagram-desktop-break"> Auf Instagram zeigen wir, was Menschen in grünen Berufen beschäftigt.</p></div><a class="instagram-profile" href="${gcInstagramProfile}" target="_blank" rel="noopener noreferrer" aria-label="@greencareers.de auf Instagram entdecken (neuer Tab)"><span class="instagram-avatar"><img src="assets/logo-dark-sm.png" alt="" width="69" height="42"></span><span><strong>@greencareers.de</strong><small>Auf Instagram entdecken ${fi('up')}</small></span></a></div><div class="instagram-feed-label"><span>Aus unserem Feed</span><span>Beiträge zu Arbeitgebern, Bewerbungen und Arbeitsalltag.</span></div><ul class="instagram-grid" id="instagram-posts" tabindex="0" aria-label="Ausgewählte Instagram-Beiträge">${gcFeaturedPosts.map(post=>`<li><a class="instagram-post" href="${post.url}" target="_blank" rel="noopener noreferrer" aria-label="${post.title} Auf Instagram ansehen (neuer Tab)"><div class="instagram-post-image"><img src="assets/instagram/${post.image}" alt="${post.alt}" width="1080" height="1350" loading="lazy" decoding="async"></div><div class="instagram-post-body"><div class="instagram-post-meta"><span>${post.topic}${post.slides>1?' · 4 Slides':''}</span><time datetime="${post.date}">${post.displayDate}</time></div><h3>${post.title}</h3><span class="instagram-post-link">${post.slides>1?'Karussell ansehen':'Beitrag ansehen'} ${fi('up')}</span></div></a></li>`).join('')}</ul><div class="instagram-bottom"><a class="instagram-follow" href="${gcInstagramProfile}" target="_blank" rel="noopener noreferrer">${instagramIcon()} Mehr von Green Careers ${fi('up')}</a><div class="instagram-controls" aria-label="Beiträge durchblättern"><span id="instagram-position" aria-live="polite" aria-atomic="true">Beitrag 1 von 4</span><button type="button" data-instagram-direction="-1" aria-label="Vorherigen Instagram-Beitrag anzeigen" aria-controls="instagram-posts">${fi('arrow')}</button><button type="button" data-instagram-direction="1" aria-label="Nächsten Instagram-Beitrag anzeigen" aria-controls="instagram-posts">${fi('arrow')}</button></div><span class="instagram-bottom-note">Alle Beiträge auf unserem Instagram-Profil.</span></div></div></section>`}
let cleanupInstagram=()=>{};
function bindInstagram(){cleanupInstagram();const grid=document.querySelector('#instagram-posts');if(!grid)return;const items=[...grid.children],buttons=[...document.querySelectorAll('[data-instagram-direction]')],counter=document.querySelector('#instagram-position');let frame;
 const step=()=>items.length>1?items[1].offsetLeft-items[0].offsetLeft:1;
 const position=()=>Math.max(0,Math.min(items.length-1,Math.round(grid.scrollLeft/step())));
 const update=()=>{frame=undefined;const active=position(),max=grid.scrollWidth-grid.clientWidth;counter.textContent=`Beitrag ${active+1} von ${items.length}`;buttons.forEach(b=>b.disabled=max<2||(Number(b.dataset.instagramDirection)<0?grid.scrollLeft<2:grid.scrollLeft>=max-2));};
 const move=direction=>{const next=Math.max(0,Math.min(items.length-1,position()+direction));grid.scrollTo({left:next*step(),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update);};
 const onKey=e=>{if(e.target!==grid||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();move(e.key==='ArrowRight'?1:-1);};
 buttons.forEach(b=>b.onclick=()=>move(Number(b.dataset.instagramDirection)));grid.addEventListener('scroll',onScroll,{passive:true});grid.addEventListener('keydown',onKey);
 const resize=typeof ResizeObserver!=='undefined'?new ResizeObserver(update):null;resize?.observe(grid);update();cleanupInstagram=()=>{resize?.disconnect();if(frame)cancelAnimationFrame(frame);grid.removeEventListener('scroll',onScroll);grid.removeEventListener('keydown',onKey);};
}
