/* Public package comparison. No purchase is made in this preview. */
const gcPricing={once:[2190,3190,5490],discounts:[0,0,10,20,30],months:[2,2,3],onceVat:'unconfirmed',source:'https://www.green-careers.de/arbeitgeber'};
const gcPackages=[
 {name:'Smart',symbol:'leaf',purpose:'Für einfache und saisonale Stellen.',examples:'Helfer · Saisonkräfte',features:['Anzeige mit Bildern und Videos','Zugang zum grünen Karrierenetzwerk','KI-Filterung der Bewerbungen','Bewerbung über ein kurzes Kontaktformular']},
 {name:'Premium',symbol:'search',purpose:'Für qualifizierte Fachkräfte.',examples:'Facharbeiter · Vorarbeiter',features:['Platzierung oben in der Ergebnisliste','Auffallende Premium-Darstellung','Einbindung Ihrer Karriereseite','Einbindung Ihrer Social-Media-Kanäle']},
 {name:'Excellence',symbol:'people',purpose:'Für besonders anspruchsvolle Positionen.',examples:'Bauleiter · Kalkulator · Landschaftsarchitekt',features:['Direkte Ansprache auf Premium-Karrierenetzwerken','Branchenrelevante Recruiting-Partner','Vorqualifizierung aller Bewerber']}
];
let priceQuantity=1;
const priceMoney=cents=>(cents/100).toLocaleString('de-DE',{minimumFractionDigits:cents%100?2:0,maximumFractionDigits:2});
function gcPriceCalculation(index,quantity=priceQuantity){const base=gcPricing.once[index]*100,discount=gcPricing.discounts[quantity],unit=Math.round(base*(100-discount)/100);return {unit,amount:unit*quantity,total:unit*quantity,discount,base}}
function priceTax(){return gcPricing.onceVat==='net'?'netto · zzgl. USt.':gcPricing.onceVat==='gross'?'inkl. USt.':''}
function pricingSection(){return `<section class="section gc-pricing" id="preise" aria-labelledby="price-title"><div class="container"><div class="pricing-heading"><div><div class="eyebrow">KLARE PAKETE. EINMAL INVESTIEREN.</div><h2 id="price-title">Gute Leute finden.<br><em>Mit dem passenden Plan.</em></h2></div><p>Smart, Premium oder Excellence.<br>Wählen Sie das passende Paket für Ihre offenen Stellen.</p></div><div class="price-settings"><div class="price-quantity"><span class="price-setting-label" id="qty-label">Wie viele Stellen?</span><div class="price-segment" role="group" aria-labelledby="qty-label">${[1,2,3,4].map(n=>`<button data-price-quantity="${n}" aria-pressed="${priceQuantity===n}" aria-label="${n} ${n===1?'Stelle':'Stellen'}">${n}</button>`).join('')}</div><span class="price-quantity-note" id="price-discount-note">${priceQuantity>1?gcPricing.discounts[priceQuantity]+' % Mengenrabatt':'Bis zu 30 % Mengenrabatt'}</span></div><div class="price-once-hint">${fi('check')}<span>Einmalige Zahlung.<br><strong>Keine automatische Verlängerung.</strong></span></div></div><p class="price-live-summary sr-only" id="price-live-summary" aria-live="polite" aria-atomic="true"></p><div class="pricing-cards" id="pricing-cards">${gcPackages.map((p,i)=>priceCard(i)).join('')}</div><div class="pricing-footnotes">${pricingFootnotes()}</div><div class="pricing-advice"><div class="advice-mark">${fi('people')}</div><div><h3>Noch unsicher, welches Paket passt?</h3><p>Besprechen Sie Ihre offenen Stellen mit uns.</p></div><a class="btn" href="https://www.green-careers.de/arbeitgeber#beratungstermin-vereinbaren" target="_blank" rel="noopener">Persönlich beraten lassen ${fi('up')}</a></div></div></section>`}
function priceCard(i){const p=gcPackages[i],c=gcPriceCalculation(i);return `<article class="pricing-card ${i===1?'pricing-featured':''}" data-price-card="${i}" aria-labelledby="package-title-${i}"><div class="package-top"><span class="package-symbol">${fi(p.symbol)}</span><span class="package-tag">${i===1?'MEHR SICHTBARKEIT':'0'+(i+1)+' / EINMALPAKET'}</span></div><h3 id="package-title-${i}">${p.name}</h3><p class="package-purpose">${p.purpose}<span>${p.examples}</span></p><div class="package-price"><span class="package-amount">${priceMoney(c.amount)}</span><span class="package-currency">€</span></div><p class="package-price-unit">einmalig · für ${priceQuantity} ${priceQuantity===1?'Stelle':'Stellen'}</p><p class="package-tax">${priceTax()||'Preis gemäß aktuellem Angebot'}</p><div class="package-commitment"><div><span>Anzeigenlaufzeit</span><strong>${gcPricing.months[i]} Monate</strong></div><div><span>Zusätzlicher Garantemonat*</span><strong>inklusive</strong></div>${priceQuantity>1?`<p>${c.discount} % Mengenrabatt · ${priceMoney(c.unit)} € je Stelle</p>`:''}</div><button class="btn package-select" data-price-select="${i}">${p.name} auswählen ${fi('arrow')}</button><div class="package-features"><h4>${i===0?'Im Paket enthalten':i===1?'Alles aus Smart, zusätzlich':'Alles aus Premium, zusätzlich'}</h4><ul>${p.features.map(f=>`<li>${fi('check')}<span>${f}</span></li>`).join('')}</ul></div></article>`}
function pricingFootnotes(){return `<p>${fi('check')} Einmalige Zahlung · Kreditkarte, PayPal oder Kauf auf Rechnung${priceTax()?' · '+priceTax():''}</p><p>* Ein zusätzlicher Garantemonat, falls die gesuchte Person innerhalb der regulären Laufzeit nicht eingestellt wurde. Der Garantemonat verlängert die Laufzeit; eine Einstellung wird nicht zugesagt. <a href="https://www.green-careers.de/arbeitgeber" target="_blank" rel="noopener">Angebotsdetails ansehen ↗</a></p>`}
function updatePriceCards(){$('#pricing-cards').innerHTML=gcPackages.map((p,i)=>priceCard(i)).join('');$$('[data-price-quantity]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.priceQuantity)===priceQuantity)));$('#price-discount-note').textContent=priceQuantity>1?gcPricing.discounts[priceQuantity]+' % Mengenrabatt':'Bis zu 30 % Mengenrabatt';$('#price-live-summary').textContent=`${priceQuantity} ${priceQuantity===1?'Stelle':'Stellen'}. `+gcPackages.map((p,i)=>p.name+' '+priceMoney(gcPriceCalculation(i).amount)+' Euro einmalig').join('. ');bindPackageSelection()}
function showPrices(){$('#preise').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#price-title').setAttribute('tabindex','-1');$('#price-title').focus({preventScroll:true})}
function bindPackageSelection(){$$('[data-price-select]').forEach(b=>b.onclick=()=>priceSelection(Number(b.dataset.priceSelect)))}
function priceSelection(i){const p=gcPackages[i],c=gcPriceCalculation(i);openModal(`<div class="modal-kicker">IHRE PAKETAUSWAHL</div><h2 id="modal-title">${p.name}.<br>Gezielt sichtbar.</h2><div class="price-modal-summary"><div class="requested-position" id="requested-position" hidden><span>Gesuchte Position</span><strong id="requested-position-text"></strong></div><div><span>Zahlungsmodell</span><strong>Einmalzahlung</strong></div><div><span>Stellen</span><strong>${priceQuantity}</strong></div><div><span>Anzeigenlaufzeit</span><strong>${gcPricing.months[i]} Monate</strong></div>${c.discount?`<div><span>Mengenrabatt</span><strong>${c.discount} %</strong></div>`:''}<div><span>Einmaliger Paketpreis</span><strong>${priceMoney(c.amount)} €</strong></div></div><p class="price-modal-tax">${priceTax()||'Preis gemäß aktueller Green-Careers-Angebotsseite.'}</p><p class="price-guarantee-note">Ein zusätzlicher Garantemonat, falls die gesuchte Person innerhalb der regulären Laufzeit nicht eingestellt wurde.</p><p>Die Buchung erfolgt auf der bestehenden Green-Careers-Seite. Dort wählen Sie Ihr Paket und bestätigen die Zahlungs- und Vertragsdetails.</p><a class="btn price-modal-link" href="${gcPricing.source}" target="_blank" rel="noopener">Originalangebot öffnen ${fi('up')}</a><button class="text-link price-modal-back" id="price-modal-back">Weiter vergleichen</button><p class="demo-note">Designvorschau · Mit dieser Auswahl wurde nichts gebucht.</p>`);const role=$('#quick-role')?.value.trim();if(role){$('#requested-position').hidden=false;$('#requested-position-text').textContent=role}$('#price-modal-back').onclick=()=>modal.close()}
function bindPricing(){if(theme!=='e'||audience!=='employer')return;$$('[data-price-quantity]').forEach(b=>b.onclick=()=>{priceQuantity=Number(b.dataset.priceQuantity);updatePriceCards()});$$('[data-price-entry]').forEach(b=>b.onclick=showPrices);['consult','network-start'].forEach(id=>$('#'+id).onclick=()=>{startEmployer();$('#employer-role').value=$('#quick-role').value});$('#start-employer').onclick=showPrices;$('#footer-primary').onclick=showPrices;$('[data-offer="Stellenanzeige"]').onclick=showPrices;bindPackageSelection()}
