/* Prices verified against the two live Green Careers offer pages on 2026-09-15.
   No checkout requests are created by this design preview. */
const gcPricing = {
  once: [2190,3190,5490],
  subscription: {6:[499,699,899],12:[399,559,719],24:[349,489,629]},
  discounts: [0,0,10,20,30],
  days: [60,60,90],
  onceVat: 'unconfirmed',
  sources: {once:'https://www.green-careers.de/arbeitgeber',subscription:'https://abo.green-careers.de/#pakete'}
};
const gcPackages = [
  {name:'Smart',symbol:'leaf',purpose:'Für einfache und saisonale Stellen.',examples:'Helfer · Saisonkräfte',once:['Anzeige mit Bildern und Videos','Zugang zum grünen Karrierenetzwerk','KI-Filterung der Bewerbungen','Bewerbung über ein kurzes Kontaktformular','30-Tage-Zufriedenheitsgarantie gemäß Angebot'],subscription:['Anzeige mit Bildern und Videos','Zugang zum grünen Karrierenetzwerk','KI-Filterung der Bewerbungen','Bewerbungen per E-Mail und WhatsApp','Fester Ansprechpartner']},
  {name:'Premium',symbol:'search',purpose:'Für qualifizierte Fachkräfte.',examples:'Facharbeiter · Vorarbeiter',once:['Platzierung oben in der Ergebnisliste','Auffallende Premium-Darstellung','Einbindung Ihrer Karriereseite','Einbindung Ihrer Social-Media-Kanäle'],subscription:['Ausspielung auf allen Social-Media-Kanälen','Premium-Platzierung und Darstellung','Einbindung Ihrer Karriereseite','Erweitertes Targeting im DACH-Raum']},
  {name:'Exzellenz',symbol:'people',purpose:'Für besonders anspruchsvolle Positionen.',examples:'Bauleiter · Kalkulator · Landschaftsarchitekt',once:['Direkte Ansprache auf Premium-Karrierenetzwerken','Branchenrelevante Recruiting-Partner','Vorqualifizierung aller Bewerber'],subscription:['Direkte Ansprache auf Premium-Karrierenetzwerken','Branchenrelevante Recruiting-Partner','Vorqualifizierung aller Bewerber','Persönlicher Senior-Recruiter','Reichweite über die GreenCareers-Community']}
];
let priceMode='once', priceTerm=6, priceQuantity=1;
const priceMoney = cents => (cents/100).toLocaleString('de-DE',{minimumFractionDigits:cents%100?2:0,maximumFractionDigits:2});
function gcPriceCalculation(index,mode=priceMode,term=priceTerm,quantity=priceQuantity){
  const base=(mode==='once'?gcPricing.once:gcPricing.subscription[term])[index]*100;
  const discount=gcPricing.discounts[quantity];
  const unit=Math.round(base*(100-discount)/100);
  return {unit,amount:unit*quantity,total:unit*quantity*(mode==='once'?1:term),discount,base};
}
function priceTax(mode=priceMode){return mode==='subscription'||gcPricing.onceVat==='net'?'netto · zzgl. USt.':gcPricing.onceVat==='gross'?'inkl. USt.':''}
function pricingSection(){return `<section class="section gc-pricing" id="preise" aria-labelledby="price-title"><div class="container"><div class="pricing-heading"><div><div class="eyebrow">PAKETE & PREISE FÜR IHREN BETRIEB</div><h2 id="price-title">Gute Leute finden.<br><em>Mit dem passenden Plan.</em></h2></div><p>Eine Stelle besetzen oder dauerhaft sichtbar bleiben. Wählen Sie den Weg, der zu Ihrem Personalbedarf passt.</p></div><div class="price-modes" role="group" aria-label="Zahlungsmodell auswählen"><button data-price-mode="once" aria-pressed="${priceMode==='once'}"><span class="mode-icon">${fi('arrow')}</span><span><strong>Einmalzahlung</strong><small>Gezielt eine Stelle besetzen</small></span><span class="mode-selected">${fi('check')}</span></button><button data-price-mode="subscription" aria-pressed="${priceMode==='subscription'}"><span class="mode-icon">${fi('leaf')}</span><span><strong>Recruiting-Abo</strong><small>Kontinuierlich Fachkräfte erreichen</small></span><span class="mode-selected">${fi('check')}</span></button></div><div class="price-settings"><div class="price-quantity"><span class="price-setting-label" id="qty-label">Wie viele Stellen?</span><div class="price-segment" role="group" aria-labelledby="qty-label">${[1,2,3,4].map(n=>`<button data-price-quantity="${n}" aria-pressed="${priceQuantity===n}" aria-label="${n} ${n===1?'Stelle':'Stellen'}">${n}</button>`).join('')}</div><span class="price-quantity-note" id="price-discount-note">${priceQuantity>1?gcPricing.discounts[priceQuantity]+' % Mengenrabatt':'Bis zu 30 % Mengenrabatt'}</span></div><div class="price-duration" id="price-duration" ${priceMode==='once'?'hidden':''}><span class="price-setting-label" id="term-label">Welche Laufzeit?</span><div class="price-segment term-segment" role="group" aria-labelledby="term-label">${[6,12,24].map(n=>`<button data-price-term="${n}" aria-pressed="${priceTerm===n}">${n} Monate</button>`).join('')}</div></div><div class="price-once-hint" id="price-once-hint" ${priceMode==='subscription'?'hidden':''}>${fi('check')}<span>Feste Laufzeit.<br><strong>Keine automatische Verlängerung.</strong></span></div></div><p class="price-live-summary sr-only" id="price-live-summary" aria-live="polite" aria-atomic="true"></p><div class="pricing-cards" id="pricing-cards">${gcPackages.map((p,i)=>priceCard(i)).join('')}</div><div class="pricing-footnotes" id="pricing-footnotes">${pricingFootnotes()}</div><div class="pricing-advice"><div class="advice-mark">${fi('people')}</div><div><h3>Noch unsicher, welches Paket passt?</h3><p>Besprechen Sie Ihre offenen Stellen mit uns.</p></div><a class="btn" href="https://www.green-careers.de/arbeitgeber#beratungstermin-vereinbaren" target="_blank" rel="noopener">Persönlich beraten lassen ${fi('up')}</a></div></div></section>`}
function priceCard(i){const p=gcPackages[i],c=gcPriceCalculation(i),abo=priceMode==='subscription';return `<article class="pricing-card ${i===1?'pricing-featured':''}" data-price-card="${i}" aria-labelledby="package-title-${i}"><div class="package-top"><span class="package-symbol">${fi(p.symbol)}</span><span class="package-tag">${i===1?'MEHR SICHTBARKEIT':'0'+(i+1)+' / '+(abo?'RECRUITING-ABO':'EINMALPAKET')}</span></div><h3 id="package-title-${i}">${p.name}</h3><p class="package-purpose">${p.purpose}<span>${p.examples}</span></p><div class="package-price"><span class="package-amount">${priceMoney(c.amount)}</span><span class="package-currency">€</span></div><p class="package-price-unit">${abo?'pro Monat':'einmalig'} · für ${priceQuantity} ${priceQuantity===1?'Stelle':'Stellen'}</p><p class="package-tax">${priceTax()||'Preis gemäß aktuellem Angebot'}</p><div class="package-commitment"><div><span>${abo?'Vertragslaufzeit':'Anzeigenlaufzeit'}</span><strong>${abo?priceTerm+' Monate':gcPricing.days[i]+' Tage'}</strong></div><div><span>${abo?'Gesamt über die Laufzeit':'Gesamter Paketpreis'}</span><strong>${priceMoney(c.total)} €${abo?' netto':''}</strong></div>${priceQuantity>1?`<p>${c.discount} % Mengenrabatt · ${priceMoney(c.unit)} € je Stelle${abo?' / Monat':''}</p>`:''}</div><button class="btn package-select" data-price-select="${i}">${p.name} auswählen ${fi('arrow')}</button><div class="package-features"><h4>${i===0?'Im Paket enthalten':i===1?'Alles aus Smart, zusätzlich':'Alles aus Premium, zusätzlich'}</h4><ul>${p[priceMode].map(f=>`<li>${fi('check')}<span>${f}</span></li>`).join('')}</ul></div></article>`}
function pricingFootnotes(){return priceMode==='subscription'?`<p>${fi('check')} Monatliche Abbuchung · Keine Setup-Gebühren · Alle Preise netto zzgl. USt.</p><p>Kreditkarte oder SEPA-Lastschrift. Die gewählte Laufzeit gilt für das gesamte Abo. <a href="https://www.green-careers.de/agb" target="_blank" rel="noopener">Vertragsbedingungen ansehen ↗</a></p>`:`<p>${fi('check')} Einmalige Zahlung · Kreditkarte, PayPal oder Kauf auf Rechnung${priceTax()?' · '+priceTax():''}</p><p>Smart und Premium: 60 Tage · Exzellenz: 90 Tage. Die Zufriedenheitsgarantie richtet sich nach dem Originalangebot. <a href="https://www.green-careers.de/arbeitgeber" target="_blank" rel="noopener">Angebotsdetails ansehen ↗</a></p>`}
function updatePriceCards(){
  $('#pricing-cards').innerHTML=gcPackages.map((p,i)=>priceCard(i)).join('');
  $('#pricing-footnotes').innerHTML=pricingFootnotes();
  $('#price-duration').hidden=priceMode==='once';$('#price-once-hint').hidden=priceMode==='subscription';
  $$('[data-price-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.priceMode===priceMode)));
  $$('[data-price-term]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.priceTerm)===priceTerm)));
  $$('[data-price-quantity]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.priceQuantity)===priceQuantity)));
  $('#price-discount-note').textContent=priceQuantity>1?gcPricing.discounts[priceQuantity]+' % Mengenrabatt':'Bis zu 30 % Mengenrabatt';
  $('#price-live-summary').textContent=`${priceMode==='once'?'Einmalzahlung':'Abo, '+priceTerm+' Monate'}, ${priceQuantity} ${priceQuantity===1?'Stelle':'Stellen'}. `+gcPackages.map((p,i)=>p.name+' '+priceMoney(gcPriceCalculation(i).amount)+' Euro'+(priceMode==='subscription'?' pro Monat':' einmalig')).join('. ');
  bindPackageSelection();
}
function showPrices(mode){if(mode){priceMode=mode;updatePriceCards()}$('#preise').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('#price-title').setAttribute('tabindex','-1');$('#price-title').focus({preventScroll:true})}
function bindPackageSelection(){$$('[data-price-select]').forEach(b=>b.onclick=()=>priceSelection(Number(b.dataset.priceSelect)))}
function priceSelection(i){const p=gcPackages[i],c=gcPriceCalculation(i),abo=priceMode==='subscription';openModal(`<div class="modal-kicker">IHRE PAKETAUSWAHL</div><h2 id="modal-title">${p.name}.<br>${abo?'Kontinuierlich sichtbar.':'Gezielt sichtbar.'}</h2><div class="price-modal-summary"><div class="requested-position" id="requested-position" hidden><span>Gesuchte Position</span><strong id="requested-position-text"></strong></div><div><span>Zahlungsmodell</span><strong>${abo?'Recruiting-Abo':'Einmalzahlung'}</strong></div><div><span>Stellen</span><strong>${priceQuantity}</strong></div><div><span>${abo?'Vertragslaufzeit':'Anzeigenlaufzeit'}</span><strong>${abo?priceTerm+' Monate':gcPricing.days[i]+' Tage'}</strong></div>${c.discount?`<div><span>Mengenrabatt</span><strong>${c.discount} %</strong></div>`:''}<div><span>${abo?'Monatlicher Beitrag':'Einmaliger Paketpreis'}</span><strong>${priceMoney(c.amount)} €</strong></div>${abo?`<div class="price-modal-total"><span>Gesamt über ${priceTerm} Monate</span><strong>${priceMoney(c.total)} € netto</strong></div>`:''}</div><p class="price-modal-tax">${priceTax()||'Preis gemäß aktueller Green-Careers-Angebotsseite.'}</p><p>Die Buchung erfolgt auf der bestehenden Green-Careers-Seite. Dort wählen Sie Ihr Paket und bestätigen die Zahlungs- und Vertragsdetails.</p><a class="btn price-modal-link" href="${gcPricing.sources[priceMode]}" target="_blank" rel="noopener">Originalangebot öffnen ${fi('up')}</a><button class="text-link price-modal-back" id="price-modal-back">Weiter vergleichen</button><p class="demo-note">Designvorschau · Mit dieser Auswahl wurde nichts gebucht.</p>`);const role=$('#quick-role')?.value.trim();if(role){$('#requested-position').hidden=false;$('#requested-position-text').textContent=role}$('#price-modal-back').onclick=()=>modal.close()}
function bindPricing(){if(theme!=='e'||audience!=='employer')return;
  $$('[data-price-mode]').forEach(b=>b.onclick=()=>{priceMode=b.dataset.priceMode;updatePriceCards()});
  $$('[data-price-term]').forEach(b=>b.onclick=()=>{priceTerm=Number(b.dataset.priceTerm);updatePriceCards()});
  $$('[data-price-quantity]').forEach(b=>b.onclick=()=>{priceQuantity=Number(b.dataset.priceQuantity);updatePriceCards()});
  $$('[data-price-entry]').forEach(b=>b.onclick=()=>showPrices(b.dataset.priceEntry));
  ['consult','network-start'].forEach(id=>$('#'+id).onclick=()=>{startEmployer();$('#employer-role').value=$('#quick-role').value});$('#start-employer').onclick=()=>showPrices();$('#footer-primary').onclick=()=>showPrices();
  $('[data-offer="Stellenanzeige"]').onclick=()=>showPrices('once');
  bindPackageSelection();
}
